package program;

/*
 * jdi_branch.java
 *
 * Created on June 7, 2009, 5:55 PM
 */


//import masterfile.*;
import Main.browser.Jdi_browse_vender;
import Bean.Branchfile;
import Bean.Vender;
import DBcontrol.Db_branchfile;
import DBcontrol.Db_vender;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Point;
import java.awt.TextField;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author  root
 */
public class jdi_vendersetting extends javax.swing.JDialog {

    private int checkNameClick = 0;
    DecimalFormat doubleFmt = new DecimalFormat("##,###,##0.00");
    SimpleDateFormat thFmt = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    SimpleDateFormat enFmt = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);

    public jdi_vendersetting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        txtVCrAmount.setText("0");
        txtCrTerm.setText("0");
        btn_remove.setEnabled(false);
        txtVbusAssi.setText("0");
        txtSendTime.setText("0");
        txtVCrAmount.setValue(0);
        txtCrTerm.setValue(0);
        txtVbusAssi.setValue(0);
        txtSendTime.setValue(0);
        txtDisplayMode.setText("Normal Mode");
         txtAdressNo.setEditable(false);
        txtCharge.setEditable(false);
        txtContack.setEditable(false);
        txtCrTerm.setEditable(false);
        txtDate.setEditable(false);
        txtDep.setEditable(false);
        txtDiscount.setEditable(false);
        txtProvince.setEditable(false);
        txtEmail.setEditable(false);
        txtFax.setEditable(false);
        txtPhone.setEditable(false);
        txtPost.setEditable(false);
        txtCity.setEditable(false);
        txtRemark.setEditable(false);
        txtSendTime.setEditable(false);
        txtSubprovince.setEditable(false);
        txtTypeBus.setEditable(false);
        txtVBusNo.setEditable(false);
        txtVConPur.setEditable(false);
        txtVCrAmount.setEditable(false);
        txtVTaxNo.setEditable(false);
        txtVTran.setEditable(false);
        txtVbusAssi.setEditable(false);
        txtbk.setEditable(false);      
        txtpayType.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_addNew = new javax.swing.JButton();
        btn_cancle = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_F1_Vender = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDisplayMode = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtAdressNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSubprovince = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProvince = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPost = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtRemark = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCrTerm = new javax.swing.JFormattedTextField();
        txtVCrAmount = new javax.swing.JFormattedTextField();
        txtpayType = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtbk = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTypeBus = new javax.swing.JTextField();
        txtDate = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txtVBusNo = new javax.swing.JTextField();
        txtVTaxNo = new javax.swing.JTextField();
        txtVbusAssi = new javax.swing.JFormattedTextField();
        btn_Date = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCharge = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtContack = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtDep = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        txtVConPur = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtVTran = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtSendTime = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_Add = new javax.swing.JMenuItem();
        menu_Cancle = new javax.swing.JMenuItem();
        menu_Save = new javax.swing.JMenuItem();
        menu_Remove = new javax.swing.JMenuItem();
        menu_Remove1 = new javax.swing.JMenuItem();
        menu_exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("กำหนดแฟ้มข้อมูลผู้จำหน่าย (Vender File Setting)");
        setBackground(new java.awt.Color(236, 236, 236));
        setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_addNew.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_addNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.gif"))); // NOI18N
        btn_addNew.setText("เพิ่มเอกสาร");
        btn_addNew.setToolTipText("เพิ่มเอกสาร");
        btn_addNew.setFocusable(false);
        btn_addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addNewActionPerformed(evt);
            }
        });

        btn_cancle.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_cancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancle.gif"))); // NOI18N
        btn_cancle.setText("ยกเลิก");
        btn_cancle.setToolTipText("ยกเลิก");
        btn_cancle.setFocusable(false);
        btn_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancleActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.gif"))); // NOI18N
        btn_save.setText("บันทึกข้อมูล");
        btn_save.setToolTipText("บันทึกข้อมูล");
        btn_save.setFocusable(false);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_remove.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.gif"))); // NOI18N
        btn_remove.setText("ลบข้อมูล");
        btn_remove.setToolTipText("ลบข้อมูล");
        btn_remove.setFocusable(false);
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.gif"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_F1_Vender.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_F1_Vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying glass.jpg"))); // NOI18N
        btn_F1_Vender.setText("ผู้จำหน่าย");
        btn_F1_Vender.setToolTipText("ลบข้อมูล");
        btn_F1_Vender.setFocusable(false);
        btn_F1_Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_F1_VenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_addNew)
                .addGap(0, 0, 0)
                .addComponent(btn_cancle)
                .addGap(0, 0, 0)
                .addComponent(btn_save)
                .addGap(0, 0, 0)
                .addComponent(btn_remove)
                .addGap(0, 0, 0)
                .addComponent(btn_F1_Vender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 516, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_addNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_F1_Vender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 230, 205));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel1.setText("รหัสผู้จำหน่าย(Vender Code)");

        jLabel2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel2.setText("ชื่อผู้จำหน่าย (Vender Name)");

        txtDisplayMode.setBackground(new java.awt.Color(127, 227, 202));
        txtDisplayMode.setEditable(false);
        txtDisplayMode.setFont(new java.awt.Font("Norasi", 1, 22)); // NOI18N
        txtDisplayMode.setForeground(new java.awt.Color(255, 25, 0));
        txtDisplayMode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDisplayMode.setText("NORRMAL MODE");
        txtDisplayMode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDisplayMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDisplayModeMouseClicked(evt);
            }
        });

        txtCode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodeFocusLost(evt);
            }
        });
        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodeKeyReleased(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(txtDisplayMode, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDisplayMode, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 230, 205));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabbedPane1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel17.setText("ที่อยู่ เลขที่");

        txtAdressNo.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtAdressNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdressNoKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel5.setText("ตำบล/แขวง");

        txtSubprovince.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtSubprovince.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubprovinceKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel6.setText("เขต/อำเภอ");

        txtProvince.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtProvince.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProvinceKeyReleased(evt);
            }
        });

        txtCity.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel7.setText("รหัสไปรษณีย์");

        jLabel8.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel8.setText("จังหวัด");

        txtPost.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtPost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPostKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPostKeyReleased(evt);
            }
        });

        txtPhone.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel11.setText("โทรศัพท์");

        jLabel12.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel12.setText("เบอร์โทรสาร");

        txtFax.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxKeyReleased(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel9.setText("อี-เมลล์");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPost, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdressNo, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSubprovince, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProvince, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel17)
                    .addComponent(txtAdressNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtSubprovince, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(txtPost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(5, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel10.setText("หมายเหตุ (Remark)");

        txtRemark.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtRemark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRemarkKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtRemark, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel19.setText("ระยะเวลาเครดิต");

        jLabel20.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel20.setText("วงเงินเครดิต");

        jLabel21.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel21.setText("วิธีการชำระเงิน");

        txtCrTerm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCrTerm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCrTerm.setText("0");

        txtVCrAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtVCrAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVCrAmount.setText("0.00");

        txtpayType.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtpayType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpayTypeKeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel22.setText("เลขบัญชีธนาคาร");

        txtbk.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtbk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbkKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22))
                    .addComponent(jLabel19))
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(txtCrTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(4, 4, 4)
                        .addComponent(txtVCrAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(txtpayType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtbk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(txtVCrAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCrTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21)
                    .addComponent(txtpayType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtbk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel13.setText("ประเภทธุรกิจ");

        jLabel14.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel14.setText("วันที่จัดตั้ง");

        jLabel15.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel15.setText("เลขทะเบียนการค้า");

        jLabel16.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel16.setText("เลขประจำตัวผู้เสียภาษี");

        txtTypeBus.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtTypeBus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTypeBusKeyReleased(evt);
            }
        });

        txtDate.setEditable(false);
        txtDate.setText(" ");

        jLabel18.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel18.setText("ทุนจดทะเบียน");

        txtVBusNo.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtVBusNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVBusNoKeyReleased(evt);
            }
        });

        txtVTaxNo.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtVTaxNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVTaxNoKeyReleased(evt);
            }
        });

        txtVbusAssi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtVbusAssi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVbusAssi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVbusAssiFocusLost(evt);
            }
        });

        btn_Date.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying glass.jpg"))); // NOI18N
        btn_Date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DateMouseClicked(evt);
            }
        });
        btn_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVTaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTypeBus, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVBusNo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(txtDate)
                                .addGap(0, 0, 0)
                                .addComponent(btn_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVbusAssi, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(txtTypeBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(txtVbusAssi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Date)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15)
                    .addComponent(txtVBusNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtVTaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel23.setText("ส่วนลดการชำระเงิน");

        txtDiscount.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscountKeyReleased(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel24.setText("เบี้ยปรับชำระเกินกำหนด");

        txtCharge.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtCharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChargeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCharge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel24)
                .addGap(0, 0, 0)
                .addComponent(txtCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel25.setText("ชื่อผู้ติดต่อ");

        txtContack.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtContack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContackKeyReleased(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel26.setText("แผนก/ฝ่าย");

        txtDep.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDepKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(txtContack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(0, 0, 0)
                .addComponent(txtContack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel26)
                .addGap(0, 0, 0)
                .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel27.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel27.setText("เงื่อนไขการสั่งซื้อ");

        txtVConPur.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtVConPur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVConPurKeyReleased(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel28.setText("การขนส่งสินค้า");

        txtVTran.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtVTran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVTranKeyReleased(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel29.setText("ระยะเวลาการส่งสินค้า");

        txtSendTime.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVTran, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(jLabel28)
                    .addComponent(txtVConPur, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSendTime, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29)
                    .addComponent(txtSendTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(txtVConPur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel28)
                .addGap(0, 0, 0)
                .addComponent(txtVTran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ข้อมูลทั่วไป (Generial)", jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("ฟังก์ชัน (Function)");
        jMenu1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N

        menu_Add.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menu_Add.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Add.setText("เพิ่มข้อมูลใหม่ (Add New)");
        menu_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_AddActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Add);

        menu_Cancle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menu_Cancle.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Cancle.setText("ยกเลิกการแก้ไข (Cancle All)");
        menu_Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CancleActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Cancle);

        menu_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_Save.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Save.setText("บันทึกข้อมูล (Save/Update)");
        menu_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_SaveActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Save);

        menu_Remove.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menu_Remove.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Remove.setText("ลบข้อมูล (Remove)");
        menu_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_RemoveActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Remove);

        menu_Remove1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menu_Remove1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Remove1.setText("แสดงรายการ (List)");
        menu_Remove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Remove1ActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Remove1);

        menu_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menu_exit.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_exit.setText("ออกจากการทำงาน (Exit)");
        menu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exitActionPerformed(evt);
            }
        });
        jMenu1.add(menu_exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("รายงาน (Report)");
        jMenu2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenu3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1024, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btn_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancleActionPerformed
// TODO add your handling code here:
    clearForm();
}//GEN-LAST:event_btn_cancleActionPerformed

private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_btn_exitActionPerformed

private void btn_addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addNewActionPerformed
// TODO add your handling code here:
    clearForm();
}//GEN-LAST:event_btn_addNewActionPerformed

private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
// TODO add your handling code here:
    txtName.requestFocus();
    
    if (txtCode.getText().trim().length() > 4 || txtCode.getText().trim().length() < 4) {
        JOptionPane.showMessageDialog(this, "รหัสผู้จำหน่ายไม่ถูกต้อง กรุณาระบุรหัสผู้จำหน่ายจำนวน 4 หลัก", "Mycps", JOptionPane.WARNING_MESSAGE);
        txtCode.requestFocus();
    } else if (txtName.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(this, "กรุณาระบุชื่อชื่อจำหน่าย", "Mycps", JOptionPane.WARNING_MESSAGE);
        txtName.requestFocus();
    } else if (txtPost.getText().trim().length() > 0 && txtPost.getText().trim().length() < 5) {
        JOptionPane.showMessageDialog(this, "รหัสไปรษณีย์ไม่ถูกต้อง", "Mycps", JOptionPane.WARNING_MESSAGE);
        txtPost.requestFocus();
    } else if (txtPost.getText().trim().length() > 5) {
        JOptionPane.showMessageDialog(this, "รหัสไปรษณีย์ไม่ถูกต้อง", "Mycps", JOptionPane.WARNING_MESSAGE);
        txtPost.requestFocus();
    } else if (txtSendTime.getText().trim().length() == 0) {
        JOptionPane.showMessageDialog(this, "กรุณาระบุระยะเวลาการส่งสินค้า", "Mycps", JOptionPane.WARNING_MESSAGE);
        txtSendTime.requestFocus();
    } else { 
        Db_vender vender = new Db_vender();
        Vender bean = new Vender();
        bean.setVname(txtName.getText());
        bean.setVaddress(txtAdressNo.getText());
        bean.setVCity(txtCity.getText());
        bean.setVSubProvince(txtSubprovince.getText());
        bean.setVProvince(txtProvince.getText());
        bean.setVPost(txtPost.getText());
        bean.setVTel(txtPhone.getText());
        bean.setVFax(txtFax.getText());
        bean.setVEmail(txtEmail.getText());
        bean.setVContack(txtContack.getText());
        bean.setVDept(txtDep.getText());
        try {
            int time = Integer.parseInt(txtSendTime.getValue().toString());
            if (time <= 0) {
                bean.setVSendTime("0");
            } else {
                bean.setVSendTime(txtSendTime.getValue().toString());
            }
        } catch (Exception e) {
            bean.setVSendTime("0");
        }
        bean.setVConPur(txtVConPur.getText());
        bean.setVTran(txtVTran.getText());
        bean.setVBusType(txtTypeBus.getText());
        bean.setVBusAssi(txtVbusAssi.getValue().toString());
        bean.setVBusBegin(txtDate.getText());
        bean.setVBusNo(txtVBusNo.getText());
        bean.setVTaxNo(txtVTaxNo.getText());
        bean.setVCrTerm(txtCrTerm.getText());
        try {
            Float amout = Float.parseFloat(txtVCrAmount.getValue().toString());
            if (amout <= 0) {
                bean.setVCrAmount("0.00");
            } else {
                bean.setVCrAmount(txtVCrAmount.getValue().toString());
            }
        } catch (Exception e) {
             bean.setVCrAmount("0.00");
        }

        bean.setVPayType(txtpayType.getText());
        bean.setVBankAcc(txtbk.getText());
        bean.setVDiscount(txtDiscount.getText());
        bean.setVCharge(txtCharge.getText());
        bean.setVRemark(txtRemark.getText());
        bean.setVCode(txtCode.getText());
        String mode = "";
        if (txtDisplayMode.getText().trim().equals("Update Mode")) {
            mode = "update";
            if (vender.inSertVender(bean, mode)) {
                JOptionPane.showMessageDialog(this, "แก้ไขข้อมูลผู้จำหน่ายแล้ว");
                clearForm();
            }
        } else {
            mode = "insert";
            if (vender.inSertVender(bean, mode)) {
                JOptionPane.showMessageDialog(this, "บันทึกข้อมูลผู้จำหน่ายแล้ว");
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "เกิดความขัดข้องของระบบไม่สามารถบันทึกข้อมูลได้");
            }
        }

    }


}//GEN-LAST:event_btn_saveActionPerformed

private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
// TODO add your handling code here:
    Db_vender vender = new Db_vender();
    int confirm = JOptionPane.showConfirmDialog(this, "คุณต้องการลบข้อมูลรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        if (vender.removeVenderFile(txtCode.getText())) {
            JOptionPane.showMessageDialog(this, "ระบบลบข้อมูลผู้จำหน่าย" + txtName.getText() + "แล้ว");
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "ระบบไม่สามารถลบข้อมูลผู้จำหน่าย " + txtName.getText() + " ได้ เนื่องจากมีการนำไปใช้งานแล้ว", "Mycps", JOptionPane.ERROR_MESSAGE);
        }
    }

}//GEN-LAST:event_btn_removeActionPerformed

private void menu_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_AddActionPerformed
// TODO add your handling code here:
    btn_saveActionPerformed(null);
}//GEN-LAST:event_menu_AddActionPerformed

private void menu_CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CancleActionPerformed
// TODO add your handling code here:
    clearForm();
}//GEN-LAST:event_menu_CancleActionPerformed

private void menu_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_SaveActionPerformed
// TODO add your handling code here:
    btn_saveActionPerformed(evt);
}//GEN-LAST:event_menu_SaveActionPerformed

private void menu_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_RemoveActionPerformed
// TODO add your handling code here:
    btn_removeActionPerformed(evt);
}//GEN-LAST:event_menu_RemoveActionPerformed

private void menu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exitActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_menu_exitActionPerformed

private void txtCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyReleased
// TODO add your handling code here:
    String Code = txtCode.getText();
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        getDataToForm(Code);
        txtCode.setBackground(new java.awt.Color(250, 217, 184));
        txtName.requestFocus();
        
        startForm();

    } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
        btn_F1_VenderActionPerformed(null);
    }


}//GEN-LAST:event_txtCodeKeyReleased

private void btn_F1_VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_F1_VenderActionPerformed
    Jdi_browse_vender vender = new Jdi_browse_vender(new Frame(), true);
    vender.setVisible(true);
    String vCode = vender.getVcode();
    if (vCode != null) {
        getDataToForm(vCode);
        txtCode.setBackground(new java.awt.Color(250, 217, 184));
        txtName.requestFocus();
        startForm();
    } else {
        txtCode.requestFocus();
    }

}//GEN-LAST:event_btn_F1_VenderActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    txtCode.requestFocus();
}//GEN-LAST:event_formWindowOpened

private void menu_Remove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Remove1ActionPerformed
    btn_F1_VenderActionPerformed(null);
}//GEN-LAST:event_menu_Remove1ActionPerformed

private void txtCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodeFocusLost
    if (txtCode.getText().trim().equals("")) {
        //  txtCode.requestFocus();
    }
}//GEN-LAST:event_txtCodeFocusLost

private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
    if (checkNameClick <= 0) {
        if (!txtCode.getText().trim().equals("")) {
            getDataToForm(txtCode.getText());
        }
    }

}//GEN-LAST:event_txtNameFocusGained

private void txtVTranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVTranKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtVTranKeyReleased

private void txtVConPurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVConPurKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtVConPurKeyReleased

private void txtDepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtDepKeyReleased

private void txtContackKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContackKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtContackKeyReleased

private void txtChargeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChargeKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtChargeKeyReleased

private void txtDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtDiscountKeyReleased

private void btn_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DateActionPerformed
    if(txtCode.isEditable()==false){
        
        Point point = btn_Date.getLocation();
        point.setLocation(point.getX() + 1, point.getY() + 1);
        utilities.DateChooser.DateChooserDialog dcd = new utilities.DateChooser.DateChooserDialog(null,true,point);
        dcd.setVisible(true);
        txtDate.setText(thFmt.format(dcd.getSelectedDate().getTime()));
    }else{txtCode.requestFocus();}
}//GEN-LAST:event_btn_DateActionPerformed

private void btn_DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DateMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_btn_DateMouseClicked

private void txtVbusAssiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVbusAssiFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_txtVbusAssiFocusLost

private void txtVTaxNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVTaxNoKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtVTaxNoKeyReleased

private void txtVBusNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVBusNoKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtVBusNoKeyReleased

private void txtTypeBusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTypeBusKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtTypeBusKeyReleased

private void txtbkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbkKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtbkKeyReleased

private void txtpayTypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayTypeKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtpayTypeKeyReleased

private void txtRemarkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemarkKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtRemarkKeyReleased

private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    }
}//GEN-LAST:event_txtEmailKeyReleased

private void txtFaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxKeyReleased
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    }
}//GEN-LAST:event_txtFaxKeyReleased

private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    }
}//GEN-LAST:event_txtPhoneKeyReleased

private void txtPostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPostKeyReleased
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    }
}//GEN-LAST:event_txtPostKeyReleased

private void txtPostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPostKeyPressed
// TODO add your handling code here:
    /*
    Float ser = Float.parseFloat(serArea.getText());
    if (ser <= 0) {
    serArea.setText("");
    }
    
     */
}//GEN-LAST:event_txtPostKeyPressed

private void txtCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyReleased
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    }
}//GEN-LAST:event_txtCityKeyReleased

private void txtProvinceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvinceKeyReleased
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    }
}//GEN-LAST:event_txtProvinceKeyReleased

private void txtSubprovinceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubprovinceKeyReleased
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    }
}//GEN-LAST:event_txtSubprovinceKeyReleased

private void txtAdressNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdressNoKeyReleased
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    }
}//GEN-LAST:event_txtAdressNoKeyReleased

private void txtDisplayModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDisplayModeMouseClicked
// TODO add your handling code here:
    JOptionPane.showMessageDialog(this,txtVCrAmount.getValue());
}//GEN-LAST:event_txtDisplayModeMouseClicked
    public void clearForm() {
        txtCode.requestFocus();
        txtCode.setText("");
        txtCode.setEditable(true);
        txtCode.setBackground(Color.white);
        txtAdressNo.setText("");
        txtCharge.setText("");
        txtContack.setText("");
        txtCrTerm.setText("");
        txtDate.setText("");
        txtDep.setText("");
        txtDiscount.setText("");
        txtProvince.setText("");
        txtEmail.setText("");
        txtFax.setText("");
        txtPhone.setText("");
        txtPost.setText("");
        txtCity.setText("");
        txtRemark.setText("");
        txtSendTime.setText("");
        txtSubprovince.setText("");
        txtTypeBus.setText("");
        txtVBusNo.setText("");
        txtVConPur.setText("");
        txtVCrAmount.setText("");
        txtVTaxNo.setText("");
        txtVTran.setText("");
        txtVbusAssi.setText("");
        txtbk.setText("");
        txtCode.setText("");
        txtName.setText("");
        txtpayType.setText(""); 
        
        txtAdressNo.setEditable(false);
        txtCharge.setEditable(false);
        txtContack.setEditable(false);
        txtCrTerm.setEditable(false);
        txtDate.setEditable(false);
        txtDep.setEditable(false);
        txtDiscount.setEditable(false);
        txtProvince.setEditable(false);
        txtEmail.setEditable(false);
        txtFax.setEditable(false);
        txtPhone.setEditable(false);
        txtPost.setEditable(false);
        txtCity.setEditable(false);
        txtRemark.setEditable(false);
        txtSendTime.setEditable(false);
        txtSubprovince.setEditable(false);
        txtTypeBus.setEditable(false);
        txtVBusNo.setEditable(false);
        txtVConPur.setEditable(false);
        txtVCrAmount.setEditable(false);
        txtVTaxNo.setEditable(false);
        txtVTran.setEditable(false);
        txtVbusAssi.setEditable(false);
        txtbk.setEditable(false);      
        txtpayType.setEditable(false);
        btn_remove.setEnabled(false);        
        checkNameClick = 0;
        txtDisplayMode.setText("Normal Mode");
    }
    public void startForm(){
        txtAdressNo.setEditable(true);
        txtCharge.setEditable(true);
        txtContack.setEditable(true);
        txtCrTerm.setEditable(true);
        txtDate.setEditable(true);
        txtDep.setEditable(true);
        txtDiscount.setEditable(true);
        txtProvince.setEditable(true);
        txtEmail.setEditable(true);
        txtFax.setEditable(true);
        txtPhone.setEditable(true);
        txtPost.setEditable(true);
        txtCity.setEditable(true);
        txtRemark.setEditable(true);
        txtSendTime.setEditable(true);
        txtSubprovince.setEditable(true);
        txtTypeBus.setEditable(true);
        txtVBusNo.setEditable(true);
        txtVConPur.setEditable(true);
        txtVCrAmount.setEditable(true);
        txtVTaxNo.setEditable(true);
        txtVTran.setEditable(true);
        txtVbusAssi.setEditable(true);
        txtbk.setEditable(true);      
        txtpayType.setEditable(true);
    }
    public void getDataToForm(String code) {
        Db_vender vender = new Db_vender();
        Vender bean = (Vender) vender.getVenderFile(code);
        if (bean != null) {
            checkNameClick = 1;
            txtDisplayMode.setText("Update Mode");
            txtAdressNo.setText(bean.getVaddress());
            txtCharge.setText(bean.getVCharge());
            txtContack.setText(bean.getVContack());
            txtCrTerm.setText(bean.getVCrTerm());
            Date time;
            String date = "";
            try {
                time = enFmt.parse(bean.getVBusBegin());
                date = thFmt.format(time);
                txtDate.setText(date);
            } catch (Exception ex) {
                txtDate.setText("");
            }

            txtDep.setText(bean.getVDept());
            txtDiscount.setText(bean.getVDiscount());
            txtProvince.setText(bean.getVProvince());
            txtEmail.setText(bean.getVEmail());
            txtFax.setText(bean.getVFax());
            txtPhone.setText(bean.getVTel());
            txtPost.setText(bean.getVPost());
            txtCity.setText(bean.getVCity());
            txtRemark.setText(bean.getVRemark());
            txtSendTime.setText(bean.getVSendTime());
            txtSubprovince.setText(bean.getVSubProvince());
            txtTypeBus.setText(bean.getVBusType());
            txtVBusNo.setText(bean.getVBusNo());
            txtVConPur.setText(bean.getVConPur());
            try {
                Float am = Float.parseFloat(bean.getVCrAmount());
                txtVCrAmount.setText(doubleFmt.format(am));
                txtVCrAmount.setValue(am);
            } catch (Exception e) {
                txtVCrAmount.setText("0.00");
            }

            txtVTaxNo.setText(bean.getVTaxNo());
            txtVTran.setText(bean.getVTran());
            try {
                Float bus = Float.parseFloat(bean.getVBusAssi());
                txtVbusAssi.setText(doubleFmt.format(bus));
                txtVbusAssi.setValue(bus);
            } catch (Exception e) {
                txtVbusAssi.setText("0.00");
            }

            txtbk.setText(bean.getVBankAcc());
            txtCode.setText(bean.getVCode());
            txtName.setText(bean.getVname());
            txtpayType.setText(bean.getVPayType());
            txtCode.setEditable(false);
            btn_remove.setEnabled(true);
        } else {
            txtCode.setEditable(false);
            txtDisplayMode.setText("Insert Mode");
        }

    }

    /**
     * 
     * 
     * 
     *   totArea.setText(doubleFmt.format(bean.getTot_Area())); 
    couArea.setText(doubleFmt.format(bean.getCou_Area()));
    kicArea.setText(doubleFmt.format(bean.getKic_Area()));
    serArea.setText(doubleFmt.format(bean.getTot_Area()));
    charge.setText(doubleFmt.format(bean.getCharge()));
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jdi_vendersetting dialog = new jdi_vendersetting(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Date;
    private javax.swing.JButton btn_F1_Vender;
    private javax.swing.JButton btn_addNew;
    private javax.swing.JButton btn_cancle;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menu_Add;
    private javax.swing.JMenuItem menu_Cancle;
    private javax.swing.JMenuItem menu_Remove;
    private javax.swing.JMenuItem menu_Remove1;
    private javax.swing.JMenuItem menu_Save;
    private javax.swing.JMenuItem menu_exit;
    private javax.swing.JTextField txtAdressNo;
    private javax.swing.JTextField txtCharge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtContack;
    private javax.swing.JFormattedTextField txtCrTerm;
    private javax.swing.JFormattedTextField txtDate;
    private javax.swing.JTextField txtDep;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtDisplayMode;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPost;
    private javax.swing.JTextField txtProvince;
    private javax.swing.JTextField txtRemark;
    private javax.swing.JFormattedTextField txtSendTime;
    private javax.swing.JTextField txtSubprovince;
    private javax.swing.JTextField txtTypeBus;
    private javax.swing.JTextField txtVBusNo;
    private javax.swing.JTextField txtVConPur;
    private javax.swing.JFormattedTextField txtVCrAmount;
    private javax.swing.JTextField txtVTaxNo;
    private javax.swing.JTextField txtVTran;
    private javax.swing.JFormattedTextField txtVbusAssi;
    private javax.swing.JTextField txtbk;
    private javax.swing.JTextField txtpayType;
    // End of variables declaration//GEN-END:variables
}
