package Main.browser;

import Bean.Branchfile;
import DBcontrol.Db_branchfile;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utilities.ThaiUtil;

public class jdi_browseBranchFile extends javax.swing.JDialog {

    DefaultTableModel model;
    public static String branchSelect = "";

    public jdi_browseBranchFile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        model = (DefaultTableModel) tblbranchdata.getModel();
        tblbranchdata.setShowGrid(true);
        tblbranchdata.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblbranchdata.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblbranchdata.setRowSelectionAllowed(true);
        tblbranchdata.setShowGrid(true);

        tblbranchdata.getColumnModel().getColumn(0).setPreferredWidth(140);
        tblbranchdata.getColumnModel().getColumn(1).setPreferredWidth(300);
        tblbranchdata.getColumnModel().getColumn(2).setPreferredWidth(170);
        tblbranchdata.getColumnModel().getColumn(3).setPreferredWidth(170);
        tblbranchdata.getColumnModel().getColumn(4).setPreferredWidth(200);
        JTableHeader header = tblbranchdata.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 16));
        tblbranchdata.setFont(new java.awt.Font("Norasi" , java.awt.Font.PLAIN ,14));
        tblbranchdata.setRowHeight(25);
        getBranchFile();
        tblbranchdata.setRowSelectionInterval(0,0);
    }

    private void getBranchFile() {
        Db_branchfile branch = new Db_branchfile();
        List list = branch.getBranchFile();
        int cnt = list.size();
        for (int i = 0; i < cnt; i++) {
            Branchfile bf = (Branchfile) list.get(i);
            String[] data = {bf.getBranchCode(), ThaiUtil.ASCII2Unicode(bf.getBranchName()), 
                bf.getTelNo(), bf.getFaxNo(), ThaiUtil.ASCII2Unicode(bf.getManagerName())};
            model.addRow(data);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbranchdata = new javax.swing.JTable();
        btn_ok = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("แสดงรายการสาขา (Branch)");
        setFont(new java.awt.Font("Norasi", 0, 14));

        jPanel1.setBackground(new java.awt.Color(228, 220, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblbranchdata.setFont(new java.awt.Font("Norasi", 0, 14));
        tblbranchdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัส (Branch Code)", "ชื่อสาขา (Branch Name)", "เบอร์โทรศัพท์ (Phone)", "เบอร์โทรสาร (Fax)", "ผู้จัดการร้าน / ผู้ติดต่อ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbranchdata.setRowHeight(20);
        tblbranchdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbranchdataMouseClicked(evt);
            }
        });
        tblbranchdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblbranchdataKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblbranchdataKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblbranchdata);
        tblbranchdata.getColumnModel().getColumn(0).setResizable(false);
        tblbranchdata.getColumnModel().getColumn(1).setResizable(false);
        tblbranchdata.getColumnModel().getColumn(2).setResizable(false);
        tblbranchdata.getColumnModel().getColumn(3).setResizable(false);
        tblbranchdata.getColumnModel().getColumn(4).setResizable(false);

        btn_ok.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.gif"))); // NOI18N
        btn_ok.setText("ตกลง (OK)");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(177, 18, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.gif"))); // NOI18N
        jButton1.setText("ออก (Exit)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(675, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok)
                    .addComponent(jButton1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-768)/2, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
// TODO add your handling code here:
    int row = tblbranchdata.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "ไม่มีข้อมูลที่เลือกกรุณาตรวจสอบข้อมูล", "Mycps", JOptionPane.OK_OPTION);
    } else {
        String branchCode = model.getValueAt(row, 0).toString();
        branchSelect = branchCode;
        dispose();
    }

}//GEN-LAST:event_btn_okActionPerformed

private void tblbranchdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbranchdataMouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() == 2) {
        btn_okActionPerformed(null);
    }
}//GEN-LAST:event_tblbranchdataMouseClicked

private void tblbranchdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblbranchdataKeyPressed
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        btn_okActionPerformed(null);
    }
}//GEN-LAST:event_tblbranchdataKeyPressed

private void tblbranchdataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblbranchdataKeyReleased
// TODO add your handling code here:
     if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
       dispose();
    }
}//GEN-LAST:event_tblbranchdataKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jdi_browseBranchFile dialog = new jdi_browseBranchFile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbranchdata;
    // End of variables declaration//GEN-END:variables
}
