package Main.viewreport;

import DBcontrol.MySQLConnect;
import Main.browser.jdi_showgroupfile;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import report.SnpReport;
import utilities.Format;

public class Jdi_report_adjstockGroup extends javax.swing.JDialog {
    private SnpReport report;

    public Jdi_report_adjstockGroup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initTable();
       
        report = new SnpReport();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt1 = new javax.swing.JFormattedTextField();
        txt2 = new javax.swing.JFormattedTextField();
        cmd1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmd2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmdPrint = new javax.swing.JButton();
        cmdProcess = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShow = new javax.swing.JTable();
        txtCount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("รายงานรายการสินค้า ตามกลุ่มสินค้า");

        jPanel1.setBackground(new java.awt.Color(251, 236, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setFont(new java.awt.Font("Norasi", 0, 14));

        txt1.setFont(new java.awt.Font("Norasi", 0, 14));
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
        });

        txt2.setFont(new java.awt.Font("Norasi", 0, 14));
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt2KeyPressed(evt);
            }
        });

        cmd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying glass.jpg"))); // NOI18N
        cmd1.setFocusable(false);
        cmd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Norasi", 1, 14));
        jLabel4.setText("ถึง");

        cmd2.setFont(new java.awt.Font("Norasi", 0, 14));
        cmd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying glass.jpg"))); // NOI18N
        cmd2.setFocusable(false);
        cmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cmd1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cmd2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cmd2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(cmd1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Norasi", 1, 16));
        jLabel1.setText("รหัสกลุ่มสินค้า (DEPT)");

        cmdPrint.setFont(new java.awt.Font("Norasi", 1, 14));
        cmdPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.gif"))); // NOI18N
        cmdPrint.setText("พิมพ์");
        cmdPrint.setFocusable(false);
        cmdPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintActionPerformed(evt);
            }
        });

        cmdProcess.setFont(new java.awt.Font("Norasi", 1, 14));
        cmdProcess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SandClock.png"))); // NOI18N
        cmdProcess.setText("F5-ประมวณผล");
        cmdProcess.setFocusable(false);
        cmdProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProcessActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Norasi", 1, 14));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.gif"))); // NOI18N
        jButton8.setText("Exit");
        jButton8.setFocusable(false);
        jButton8.setRequestFocusEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(cmdProcess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton8)
                    .addComponent(cmdPrint)
                    .addComponent(cmdProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        tblShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัสสินค้า", "ชื่อสินค้า", "กลุ่ม", "ชื่อกลุ่ม", "ผู้ขาย", "หน่วยนับ", "ราคาขาย/หน่วย", "สถานะ", "ประเภท", "ให้ส่วนลด", "ทำสต็อก", "สินค้าชุด", "คิดภาษี", "ปริมาณสูงสุดในคลัง", "ปริมาณต่ำสุดในคลัง", "โปรโมชั่น(1)", "โปรโมชั่น(2)", "โปรโมชั่น(3)", "ต้นทุน(ล่าสุด)", "ต้นทุน(เฉลี่ย)", "ต้นทุน(มาตรฐาน)", "สถานที่เก็บ", "รหัสอ้างอิง", "Acc-No", "หมายเหตุ(บันทึกข้อความ)", "ผู้จัดจำหน่าย"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblShow);

        txtCount.setFont(new java.awt.Font("Norasi", 1, 14));
        txtCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCount.setText("จำนวนรายการ 0 รายการ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-768)/2, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

private void cmd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd1ActionPerformed
    jdi_showgroupfile s = new jdi_showgroupfile(null,true);
    s.setLocation(cmd1.getLocationOnScreen());
    s.setVisible(true);
    try{
        txt1.setText(s.getValueFromShowGroupFile()[0]);
    }catch(NullPointerException ex){}
    txt1.requestFocus();
}//GEN-LAST:event_cmd1ActionPerformed

private void cmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd2ActionPerformed
    jdi_showgroupfile s = new jdi_showgroupfile(null,true);
    s.setLocation(cmd2.getLocationOnScreen());
    s.setVisible(true);
    try {
        txt2.setText(s.getValueFromShowGroupFile()[0]);
    } catch (NullPointerException ex) {}
    txt2.requestFocus();
}//GEN-LAST:event_cmd2ActionPerformed

private void cmdProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProcessActionPerformed
    resetTableModel(model);
    loadData();
}//GEN-LAST:event_cmdProcessActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    dispose();
}//GEN-LAST:event_jButton8ActionPerformed

private void cmdPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintActionPerformed
    report.adjstockGroupPrintReport(txt1.getText().trim(), txt2.getText().trim(), true);
}//GEN-LAST:event_cmdPrintActionPerformed

private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
    int key = evt.getKeyCode();
    if(key == evt.VK_F1){
        cmd1ActionPerformed(new ActionEvent(new Object(),0,""));
    }else if(key == evt.VK_F5){
        cmdProcessActionPerformed(new ActionEvent(new Object(),0,""));
    }else if(key == evt.VK_ENTER){
        txt2.requestFocus();
    }else if(key == evt.VK_ESCAPE){
        dispose();
    }
}//GEN-LAST:event_txt1KeyPressed

private void txt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyPressed
    int key = evt.getKeyCode();
    if(key == evt.VK_F1){
        cmd2ActionPerformed(new ActionEvent(new Object(),0,""));
    }else if(key == evt.VK_F5){
        cmdProcessActionPerformed(new ActionEvent(new Object(),0,""));
    }else if(key == evt.VK_ENTER){
        txt1.requestFocus();
    }else if(key == evt.VK_ESCAPE){
        dispose();
    }
}//GEN-LAST:event_txt2KeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jdi_report_adjstockGroup dialog = new Jdi_report_adjstockGroup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd1;
    private javax.swing.JButton cmd2;
    private javax.swing.JButton cmdPrint;
    private javax.swing.JButton cmdProcess;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblShow;
    private javax.swing.JFormattedTextField txt1;
    private javax.swing.JFormattedTextField txt2;
    private javax.swing.JTextField txtCount;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel model;
    
    private void resetTableModel(DefaultTableModel model){
        int rowCount = model.getRowCount();
        for(int i=0; i < rowCount; i++){
            model.removeRow(0);
        }
    }
    
    private void initTable(){
        model = (DefaultTableModel) tblShow.getModel();
        tblShow.setShowGrid(true);
        tblShow.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblShow.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblShow.setRowSelectionAllowed(true);
        tblShow.setShowGrid(true);
        tblShow.setBackground(Color.WHITE);
        tblShow.setGridColor(Color.LIGHT_GRAY);
        JTableHeader header = tblShow.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 14));
        tblShow.setFont(new java.awt.Font("Norasi" , java.awt.Font.PLAIN ,14));
        tblShow.setRowHeight(25);
        
        TableColumn column = null;
        int[] colSize = new int[tblShow.getColumnCount()];
        colSize[0] = 80;
        colSize[1] = 150;
        colSize[2] = 50;
        colSize[3] = 110;
        colSize[4] = 60;
        colSize[5] = 60;
        colSize[6] = 95;
        colSize[7] = 50;
        colSize[8] = 55;
        colSize[9] = 70;
        colSize[10] = 60;
        colSize[11] = 60;
        colSize[12] = 60;
        colSize[13] = 120;
        colSize[14] = 120;
        colSize[15] = 80;
        colSize[16] = 80;
        colSize[17] = 80;
        colSize[18] = 100;
        colSize[19] = 100;
        colSize[20] = 110;
        colSize[21] = 130;
        colSize[22] = 130;
        colSize[23] = 80;
        colSize[24] = 300;
        colSize[25] = 300;
        
        
        tblShow.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (int i = 0; i < colSize.length; i++) {
            column = tblShow.getColumnModel().getColumn(i);
            column.setPreferredWidth(colSize[i]);
        }
        
        
        TableColumnModel tcm = tblShow.getColumnModel();
        
        DefaultTableCellRenderer d;
        
        d = new DefaultTableCellRenderer();
        d.setHorizontalAlignment(SwingConstants.LEADING);
        tcm.getColumn(0).setCellRenderer(d);
        tcm.getColumn(1).setCellRenderer(d);
        tcm.getColumn(2).setCellRenderer(d);
        tcm.getColumn(3).setCellRenderer(d);
        tcm.getColumn(4).setCellRenderer(d);
        tcm.getColumn(5).setCellRenderer(d);
        tcm.getColumn(15).setCellRenderer(d);
        tcm.getColumn(16).setCellRenderer(d);
        tcm.getColumn(17).setCellRenderer(d);
        tcm.getColumn(21).setCellRenderer(d);
        tcm.getColumn(22).setCellRenderer(d);
        tcm.getColumn(23).setCellRenderer(d);
        tcm.getColumn(24).setCellRenderer(d);
        tcm.getColumn(25).setCellRenderer(d);
  
        d = new DefaultTableCellRenderer();
        d.setHorizontalAlignment(SwingConstants.CENTER);
        tcm.getColumn(7).setCellRenderer(d);
        tcm.getColumn(8).setCellRenderer(d);
        tcm.getColumn(9).setCellRenderer(d);
        tcm.getColumn(10).setCellRenderer(d);
        tcm.getColumn(11).setCellRenderer(d);
        tcm.getColumn(12).setCellRenderer(d);
        
        d = new DefaultTableCellRenderer();
        d.setHorizontalAlignment(SwingConstants.RIGHT);
        tcm.getColumn(6).setCellRenderer(d);
        tcm.getColumn(13).setCellRenderer(d);
        tcm.getColumn(14).setCellRenderer(d);
        tcm.getColumn(18).setCellRenderer(d);
        tcm.getColumn(19).setCellRenderer(d);
        tcm.getColumn(20).setCellRenderer(d);
        
        tblShow.setAutoCreateRowSorter(true);
    
    }
    
    private void loadData(){
        String group1 = txt1.getText().trim();
        String group2 = txt2.getText().trim();
        group1 = group1.equals("") ? "0" : group1;
        group2 = group2.equals("") ? "ZZZZZZZZ" : group2;
        String sql = "SELECT *" +
                " FROM product" +
                " LEFT JOIN groupfile ON pgroup = groupcode" +
                " LEFT Join vender ON pvender = vcode" +
                " WHERE (pgroup>= '"+group1+"') AND (pgroup<='"+group2+"') AND" +
                " (pstock = 'Y') AND (pactive = 'Y')" +
                " Order By pcode ";
        System.out.println(" loadData = "+sql);
        try {
            ResultSet rs = MySQLConnect.con.createStatement().executeQuery(sql);
            while(rs.next()){
                String[] row = new String[tblShow.getColumnCount()];
                
                row[0] = rs.getString("pcode");
                row[1] = rs.getString("pdesc");
                row[2] = rs.getString("pgroup");
                row[3] = rs.getString("groupname");
                row[4] = rs.getString("pvender");
                row[5] = rs.getString("punit1");
                row[6] = Format.doubleFmt.format(rs.getFloat("pprice11"));
                row[7] = rs.getString("pstatus");
                row[8] = rs.getString("pnormal");
                row[9] = rs.getString("pservice");
                row[10] = rs.getString("pstock");
                row[11] = rs.getString("pset");
                row[12] = rs.getString("pvat");
                row[13] = Format.doubleFmt.format(rs.getFloat("pmax"));
                row[14] = Format.doubleFmt.format(rs.getFloat("pmin"));
                row[15] = rs.getString("ppromotion1");
                row[16] = rs.getString("ppromotion2");
                row[17] = rs.getString("ppromotion3");
                //row[18] = rs.getFloat("plcost"));
                row[18] = Format.doubleFmt.format(rs.getFloat("plcost"));
                row[19] = Format.doubleFmt.format(rs.getFloat("pacost"));
                row[20] = Format.doubleFmt.format(rs.getFloat("pscost"));
                row[21] = rs.getString("parea");
                row[22] = rs.getString("preferent");
                row[23] = rs.getString("paccno");
                row[24] = rs.getString("premark");
                row[25] = rs.getString("vname");
                
                model.addRow(row);
                
            }
            txtCount.setText("จำนวนรายการ "+Format.integerFmt.format(tblShow.getRowCount()) + " รายการ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }
   /* 
    private void loadData2(){
        String group1 = txt1.getText().trim();
        String group2 = txt2.getText().trim();
        group1 = group1.equals("") ? "0" : group1;
        group2 = group2.equals("") ? "ZZZZZZZZ" : group2;
        String sql = "SELECT *" +
                " FROM product" +
                " LEFT JOIN groupfile ON pgroup = groupcode" +
                " LEFT Join vender ON pvender = vcode" +
                " WHERE (pgroup>= '"+group1+"') AND (pgroup<='"+group2+"') AND" +
                " (pstock = 'Y') AND (pactive = 'Y')" +
                " Order By pcode ";
        System.out.println(" loadData = "+sql);
        try {
            ResultSet rs = dbUtility.con.createStatement().executeQuery(sql);
            while(rs.next()){
                Vector row = new Vector();
                
                row.add(rs.getString("pcode"));
                row.add(rs.getString("pdesc"));
                row.add(rs.getString("pgroup"));
                row.add(rs.getString("groupname"));
                row.add(rs.getString("pvender"));
                row.add(rs.getString("punit1"));
                row.add(rs.getFloat("pprice11"));
                row.add(rs.getString("pstatus"));
                row.add(rs.getString("pnormal"));
                row.add(rs.getString("pservice"));
                row.add(rs.getString("pstock"));
                row.add( rs.getString("pset"));
                row.add(rs.getString("pvat"));
                row.add(rs.getFloat("pmax"));
                row.add(rs.getFloat("pmin"));
                row.add(rs.getString("ppromotion1"));
                row.add(rs.getString("ppromotion2"));
                row.add(rs.getString("ppromotion3"));
                row.add(rs.getFloat("plcost"));
                row.add(rs.getFloat("pacost"));
                row.add(rs.getFloat("pscost"));
                row.add(rs.getString("parea"));
                row.add(rs.getString("preferent"));
                row.add(rs.getString("paccno"));
                row.add(rs.getString("premark"));
                row.add(rs.getString("vname"));
                
                model.addRow(row);
                
            }
            txtCount.setText("จำนวนรายการ "+Format.integerFmt.format(tblShow.getRowCount()) + " รายการ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }
    * */
}
